### ISSUE TITLE
Tested Soundhax-usa.m4a on EUR.

### ISSUE THREAD

**Issue by initPRAGMA** [nedwill/soundhax#1]
So I tested it, and it just stated "Failed to play".
Im guessing different variant needs to be done for it to work on EUR?

(I put the .m4a on SD root, got the 11.2E Otherapp payload named it "otherapp.bin" and put that on SD root too, Launched Sound, Loaded the file, and "Failed to play.")

Hope this helps.

**Comment by nedwill** [comment]
Yeah, if you see the README it's USA only right now. We confirmed all regions have the vulnerability so we just need updates for the constants in constants.h/constants.py/stage2.s.

**Comment by initPRAGMA** [comment]
Oh I see, Let me know if I could be of more help. "<3 Nedwill 2016" lmao
