### ISSUE TITLE
Cant Play song O3ds

### ISSUE THREAD

**Issue by Xellc** [nedwill/soundhax#14]
when trying to play the song the Songs "app" tells me it cant be played.

**Comment by BNTK** [comment]
> We think we know why O3DS isn't working, and it has to due with different address translations in the ROP chain.

**Comment by grifnelle** [comment]
they are working on it, chill

**Comment by MagicInventor** [comment]
Just buy a n3ds

**Comment by ihaveamac** [comment]
@MagicInventor easier said than done, it would be very good to get this working on Old 3DS as well

**Comment by grifnelle** [comment]
^^^^

**Comment by joken767** [comment]
It'll work on o3DS'es, we'll just have to wait

**Comment by jt1399** [comment]
I have noticed something, it doesn't work still but when you have it in a file it will actually allow you to play it. But as I said, it still doesn't work on o3ds so continued patience and this minor issue out the way, it's time to wait like I did for slowhax... although I got nowhere with that so I started waiting for this as a primary to downgrade... hope this isn't a cycle :panic:

**Comment by HugaShire** [comment]
It is working now do what the readme says then use the Old3dsUS.m4a (or what ever format) and it should work.

**Comment by ZenBytes** [comment]
Not working for me (11.0.0-33U)

**Comment by nedwill** [comment]
Got many independent reports confirming this is working, so please make sure you followed all the steps carefully.
