### ISSUE TITLE
Is it working on N3DS-JP?

### ISSUE THREAD

**Issue by noobfromeverywhere** [nedwill/soundhax#18]
11.2.0-35J. is what I have

but I can't install it. 

is there anybody working well?

**Comment by HugaShire** [comment]
Read the Readme.

**Comment by noobfromeverywhere** [comment]
yeah... :( I had to wait more

**Comment by kaos2good** [comment]
yes it is working with the new updated sound files.

tested it on a jpn 10.7 n3ds LL

**Comment by lktom** [comment]
It's also confirmed working on o3DS JPN 11.2.

**Comment by noobfromeverywhere** [comment]
tested on 11.2.0 35J N3DS Works well.
