### ISSUE TITLE
When can we expect 11.2.0-35EU OLD3ds? 

### ISSUE THREAD

**Issue by Amidamaruu** [nedwill/soundhax#19]
I was wondering when we could expect 11.2.0-35EU on the OLD3ds?

Thanks.

**Comment by EdoCr94** [comment]
dude, just wait, they will release it soon, just chill and support them

**Comment by Amidamaruu** [comment]
Who said that I wasn't supporting them, I love what they are doing for us.

**Comment by EdoCr94** [comment]
yeah me too xD but im saying it like when we rise our arms to support Goku with the Genkidama \o/

**Comment by Mrrraou** [comment]
people like this are annoying. just wait. they're like testing stuff, debugging it and developing it. plus all the other filed issues are about this.

**Comment by BNTK** [comment]
O3DS support is here

**Comment by Konng** [comment]
And we've got N3DS EU working.. https://github.com/d3m3vilurr/soundhax/tree/support-other-regions
confirmed it myself
i tried combining the two and compiled an o3ds eu payload but it didnt work

**Comment by Konng** [comment]
Confirmed working on o3ds eu 11.1!!!! I had made a mistake when merging stuff

**Comment by Konng** [comment]
Here's the payload btw https://cdn.discordapp.com/attachments/196635745551646720/263837260011536386/soundhax.m4a

**Comment by Amidamaruu** [comment]
IT WORKS, OMG, ONE BIG LOVE TOWARDS THIS AMAZING TIME

**Comment by Amidamaruu** [comment]
IT WORKS, OMG, ONE BIG LOVE TOWARDS THIS AMAZING TEAM

**Comment by nedwill** [comment]
Fixed by @d3m3vilurr
