### ISSUE TITLE
o3ds untested still crashes

### ISSUE THREAD

**Issue by BNTK** [nedwill/soundhax#21]
when trying the new o3ds m4a it still crashes.

**Comment by BNTK** [comment]
still happens to crash however i managed to get a green screen for a second and then it went back to normal and crashed

**Comment by EzpadaZ** [comment]
Yes, new file gives me a green/red screen but it still crashes and restarts the console.

**Comment by BNTK** [comment]
same with me

**Comment by angel9990** [comment]
This one booted for me (Just made this account to comment in here :P)

**Comment by nedwill** [comment]
@angel9990 O3DS USA?

**Comment by BNTK** [comment]
I use a O3DS USA too

**Comment by angel9990** [comment]
Yes, O3DS USA 11.2 (A9LH'd btw), it booted to someone else too in GBAtemp

**Comment by BNTK** [comment]
I've even resetted my settings in music player

**Comment by nedwill** [comment]
Great, do you mind giving me a hash of the file that worked? I actually have pushed 3 versions. Or if you can just tell me from which commit your file came, that would be great (most recent one should be working)

**Comment by RuneMasterGaming** [comment]
O3ds works for me

**Comment by EzpadaZ** [comment]
WAIT IT WORKED

**Comment by nedwill** [comment]
Yeah I uploaded 3 "untested" versions in like 10 minutes. Didn't think you guys would be so fast to test :p

**Comment by EzpadaZ** [comment]
I have homebrew channel now!. The file that reads "Test again" lol, that did it first try, Thanks Ned!

**Comment by angel9990** [comment]
commit  c3a44f7 aka the Try again... one

**Comment by DoctorMacc** [comment]
Can also confirm working. o3DS USA 11.2, no AL9H. Commit d2e746b.

**Comment by DaBlueOne** [comment]
It worked, thanks so much @nedwill for your work as well as other who helped with it.

**Comment by nedwill** [comment]
Sure thing, thanks so much for the testing guys!

**Comment by skapista** [comment]
O3ds 11.0.0.33U 
HBL at first try
sd:
-starter pack
-otherapp.bin
-soundhax.m4a

**Comment by gesss** [comment]
Also made an account to tell you that it currently works on my o3ds US running 11.2.

**Comment by BNTK** [comment]
still isnt working for me tho :c

**Comment by BNTK** [comment]
THERE WE GO

**Comment by grifnelle** [comment]
just move the song onto sd right?

**Comment by lktom** [comment]
Yes.

**Comment by DoctorMacc** [comment]
@grifnelle That worked for me.

**Comment by lktom** [comment]
I can confirm working on o3DS 11.2 USA as well.

**Comment by angel9990** [comment]
Yes @grifnelle  and the otherapp.bin with your region and firmware version

**Comment by EzpadaZ** [comment]
I think we all created an account to tell ned that it works lol. Thanks for your work @nedwill

**Comment by Amidamaruu** [comment]
Please Europa next. One love from the Netherlands

**Comment by Amidamaruu** [comment]
Please Europe next. Love from the netherlands 💯 :)

**Comment by nedwill** [comment]
Thanks much for the feedback everyone, it seriously makes the process much faster. Cheers!

**Comment by grifnelle** [comment]
still crashing...

**Comment by EzpadaZ** [comment]
Use the newer file for your O3DS, with the starter kit for the hombrew loader, and your respective otherapp.bin on the root of your SD. it should load. @grifnelle

**Comment by grifnelle** [comment]
i have just downlaoded and renamed to the otherapp and i did a oot hax yesterday with the starter pack

**Comment by BNTK** [comment]
get the o3ds file

**Comment by grifnelle** [comment]
THERE WE GO
I needeed to rename the otherapp file from "pack5..." to "otherapp.bin"

**Comment by BNTK** [comment]
apparently according to some people it works on 11.1 3ds eu
