### ISSUE TITLE
Can I launch on N3DS 11.2 K ?

### ISSUE THREAD

**Issue by Jaehyeok5** [nedwill/soundhax#22]
I was waiting for this for a long time,  
but I couldn't find any words that it's working on N3DS 11.2K.
if it is simple to support for version of K ( such as change some codes) 
can I know how to launch on N3ds 11.2k?

**Comment by nedwill** [comment]
I saw a branch where a Korean version is being developed, so I believe it'll be working soon.

**Comment by Jaehyeok5** [comment]
thank you for your reply.
