### ISSUE TITLE
Get a "Could not play" error when trying to play the m4a file (O3DS 11.0.0-33U)

### ISSUE THREAD

**Issue by ZenBytes** [nedwill/soundhax#25]

**Comment by HugaShire** [comment]
We haven't confirmed usage on 11.0 and any region that is not USA.
You can only use Soundhax on 11.1 and 11.2 from the USA

**Comment by nedwill** [comment]
I got a confirmation on 11.0 N3DS. Try the updated installation instructions again carefully, and make sure to rename `otherapp.bin`.

**Comment by Karyus** [comment]
i can confirm that is working on 11.0.0-33U O3DS.

**Comment by ZenBytes** [comment]
I followed the instructions carefully and am using the right otherapp with the right name, it just won't play in the sound app. :(

**Comment by skapista** [comment]
its working, you also need the starter pack (V 2.8 Beta) and otherapp.bin, make sure you are using the last .m4a file

**Comment by ZenBytes** [comment]
Yes I have the starter pack v2.8 and the otherapp.bin named as "otherapp.bin" on the root of my SD card. It doesn't work.

**Comment by jt1399** [comment]
put the sound file in a folder, fixed it for me

**Comment by ZenBytes** [comment]
I tried that, still nothing :(

**Comment by Karyus** [comment]
launch the sound app and reset the settings and try again

**Comment by ZenBytes** [comment]
Thanks for your suggestion Karyus, I tried that but it did nothing.

**Comment by ZenBytes** [comment]
Update: I changed absolutely nothing, but it's working all of a sudden? No idea what happened but it's working fine. Thanks a lot for the help!
