### ISSUE TITLE
Can I update to the latest Firmware?

### ISSUE THREAD

**Issue by PublicMenace** [nedwill/soundhax#29]
Im asking because i want to play Pokemon online ^^

**Comment by SNKR808** [comment]
Yes, soundhax works on the latest firmware.

**Comment by PublicMenace** [comment]
Well.. I updated to 11.2.0-35E and now when i try to start Homebrew  it crashes and gives me an error message.

**Comment by ihaveamac** [comment]
replace otherapp.bin

**Comment by PublicMenace** [comment]
Ohhh right, thanks man :D Im dumb...

**Comment by kade-robertson** [comment]
If your issue is solved I believe you should be able to close this so unsolved issues can get more attention. :)
