### ISSUE TITLE
Cannot find entry symbol _start

### ISSUE THREAD

**Issue by iggyvolz** [nedwill/soundhax#3]
```bash
$ git clone git@github.com:nedwill/soundhax.git
Cloning into 'soundhax'...
*et cetera*
$ cd soundhax
$ ls
constants.h  constants.py  exp.py  README.md  soundhax-usa.m4a  stage2.s
$ python --version
Python 2.7.6
$ python exp.py
/opt/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000008000
$ ls
constants.h constants.py constants.pyc exp.py README.md soundhax.m4a soundhax-usa.m4a stage2.bin stage2.s
```

Run on WSL (Windows Subsystem for Linux aka Bash on Ubuntu on Windows). Transferring soundhax.m4a and stage2.bin (as well as otherapp.bin from https://smealum.github.io/3ds/) into the root of the SD card caused a crash but an error occured prompting a restart - not sure if this is related or not.  USA old 3DS on 11.2.0.35-U.

**Comment by nedwill** [comment]
That warning is spurious, but thanks for the report about 11.2.0-35-U not working.

**Comment by HugaShire** [comment]
where did you get the stage2.bin?

**Comment by iggyvolz** [comment]
It was generated by running python exp.py.

**Comment by HugaShire** [comment]
I didnt get the file.
