### ISSUE TITLE
Not working on 8.1.0 O3ds 

### ISSUE THREAD

**Issue by Kay6579** [nedwill/soundhax#30]
"An error has occurred which has forced the software to close". I don't know much about this stuff but someone told me that because hbl doesn't work on 8.x, an implementation of soundhax to go straight into decrypt9 is needed.

**Comment by yellows8** [comment]
It should at least display the initial otherapp screen, unless you don't even have that setup...

**Comment by Kay6579** [comment]
I guess I don't. The console is as vanilla as can be. I've been following guides and internet advisers and this is where it has brought me.

**Comment by yellows8** [comment]
https://github.com/nedwill/soundhax#status "Then put otherapp.bin on ..." Of course you'd have to test with a different otherapp-systemversion since <v9.0 isn't supported by \*hax payload.

**Comment by Kay6579** [comment]
Do I run the risk of a brick by using a different otherapp system version? If yes, is it a significant or minor risk?

**Comment by yellows8** [comment]
No, just a crash. This is only to test *soundhax* on that sysver nothing more.

**Comment by sora10pls** [comment]
Doesn't *hax 2.8 require at least 9.0?

**Comment by yellows8** [comment]
Yes, but you could test if soundhax itself works on your system if you want.

**Comment by Kay6579** [comment]
Just tried it with the 9.0.0 payload, get a quick flashing command screen "searching for target" and then "the homebrew ropbin is ready". Afterwards I'm returned to the homescreen.

**Comment by yellows8** [comment]
:)

**Comment by Kay6579** [comment]
Is that good? What do I do next? Sorry to turn this to a help forum.

**Comment by yellows8** [comment]
Actually using \*hax payload would require updating to >=v9.0 though.

**Comment by Kay6579** [comment]
Too bad. Guess its back to searching for specific 3ds cartridges in a country that doesn't seem to be a fan of nintendo. Thanks for the help.

**Comment by Kay6579** [comment]
Wait, what if I update to latest firmware version and start from there? Is that even advisable?
