### ISSUE TITLE
Tested N3DS EUR/GridLauncher

### ISSUE THREAD

**Issue by Jhynjhiruu** [nedwill/soundhax#34]
Works perfectly first try with GridLauncher, no issues whatsoever

**Comment by kade-robertson** [comment]
While it's great to be able to leave feedback, this is the Issues section of GitHub. This type of thing doesn't really belong here. You could always tweet at nedwill to let him know :)

**Comment by nedwill** [comment]
Thanks for the feedback. And yes, this should only be for bugs.
