### ISSUE TITLE
not working on all eur old 3ds

### ISSUE THREAD

**Issue by Darcyys** [nedwill/soundhax#37]
I think soundhax is not working on all old 3DS EUR
I created a guide on my website an there is people that cant get it work on OLD 3DS EUR and everything seems ok in their files . An example: https://puu.sh/t4A9W.png
Can anyone confirm this?

**Comment by kade-robertson** [comment]
I have found [these](https://www.reddit.com/r/3dshacks/comments/5kqpy6/soundhax_repo_made_public/dbqrj3v/) [two](https://www.reddit.com/r/3dshacks/comments/5kqpy6/soundhax_repo_made_public/dbqz86n/) that suggest this does work on EUR O3DS and 2DS consoles. Can you describe the error further? More detail is always better.

**Comment by Darcyys** [comment]
And i found [this comment](https://www.reddit.com/r/3dshacks/comments/5kqpy6/soundhax_repo_made_public/dbqx76l/)
and others on that reddit.
I think it is not working on all EUR consoles, its that possible?

When I try to play the file it gives me an error and the only thing i can do is restart the console.

**Comment by kade-robertson** [comment]
Oh, I just realized the issue (in the case of your screenshot). Your extensions are hidden, so your `otherapp.bin` file is actually named `otherapp.bin.bin`. Either turn on "Show hidden file extensions" in Windows Explorer and remove one of the `.bin`s or rename that file to simply be `otherapp` and try again.

**Comment by Darcyys** [comment]
That was the problem
Sorry for the confusion and thanks for your time
