### ISSUE TITLE
No hope for Korean Ver :'(?

### ISSUE THREAD

**Issue by Jaehyeok5** [nedwill/soundhax#40]
:'(

**Comment by kade-robertson** [comment]
This is not the place to be posting this. It will come whenever it can.

**Comment by KamikazePlatypus** [comment]
How old are you? These things take time. Someone told you that people are working on it, and yet here you are 12 hours later. For gods sake, be patient and refer to #41.

**Comment by nedwill** [comment]
@d3m3vilurr was working on Korean support, but had a couple issues. If he or another Korean dev can test the new constants it'll be ready. Until then, without a Korean 3DS, I can't test myself.

**Comment by BNTK** [comment]
Err... Couldn't you format your 3DS to run on Korean firmware?

**Comment by kade-robertson** [comment]
@BNTK If you happen to know where KOR ctrtransfer files are located you could, although I'm not sure I have ever seen them before.

**Comment by BNTK** [comment]
Mmm... Alright.
