### ISSUE TITLE
Not working eur o3ds.

### ISSUE THREAD

**Issue by MrHaqs** [nedwill/soundhax#42]
I put all the files in the correct places. Renamed the ropbin. Im on 10.7 o3ds. When I open the sound it flashes red green and stuff then crashes and reboots whats going on!

**Comment by kade-robertson** [comment]
You are supposed to be using the otherapp, not the ropbin.

**Comment by MrHaqs** [comment]
Its the same thing isnt it

**Comment by kade-robertson** [comment]
No, it isn't.

**Comment by MrHaqs** [comment]
ill try anyways

**Comment by MrHaqs** [comment]
oh god i apologise works now.

DOWNLOAD THE OTHERAPP NOT ROPBON MY BAD...

**Comment by MrHaqs** [comment]
ropbin*
