### ISSUE TITLE
Exp.py not making last file

### ISSUE THREAD

**Issue by HugaShire** [nedwill/soundhax#5]
It won't make the lastfile if python 3.6.0. As of result Soundhax crashes on O3DS (2DS) 11.2.0-35U

**Comment by Mrrraou** [comment]
lol use python2, check the shabang

**Comment by grifnelle** [comment]
mine makes constants.pyc but still crashes apon running the song

**Comment by nedwill** [comment]
I actually kinda prefer python3 so if people are actually using that these days I'll move it over.

**Comment by Deltanium** [comment]
Please

**Comment by Deltanium** [comment]
So, just to be sure, I drag the stage2.s file ON to the exp.py file? And it should work?

**Comment by HugaShire** [comment]
@grifnelle same here

**Comment by grifnelle** [comment]
@Deltanium, did that still crashes for me

**Comment by Deltanium** [comment]
Alright for the time being, how long can i expect till this whole thingy is fixed? Like how long can i take a break from 3DS hacking for now until this out of beta(? I guess)

**Comment by Deltanium** [comment]
Just a realization, This is for the N3DS ONLY, Not O3DS (Sadly) So. :/ Like I tested it on my N3DS, works like a charm. Tested on my O3DS, failed every time. I cry. Guess time will tell for an update for O3DS users soon

**Comment by nedwill** [comment]
We think we know why O3DS isn't working, and it has to due with different address translations in the ROP chain.

**Comment by Deltanium** [comment]
Hmm, I'll tell my friends to see if they can tweak with it

**Comment by HugaShire** [comment]
@nedwill @Deltanium Aright then, Thanks for all the help. Good Luck tweaking it
