### ISSUE TITLE
I checked on Old 3ds - KOR, SUCCESSED.

### ISSUE THREAD

**Issue by KyungsooLee** [nedwill/soundhax#52]
Soundhax is working on my KOR Old 3ds.
But it has some freezing.
I hope you fix this problem soon.
Thanks for your hard work.

**Comment by fennectech** [comment]
do you mean the yellow screen?  thats normal for any hax

**Comment by yellows8** [comment]
19d531d1e78d6c5ae30c532c2549d3909bc1e682
