### ISSUE TITLE
partial 9.2

### ISSUE THREAD

**Issue by ktn555** [nedwill/soundhax#53]
Hi 
I'm following the guide to downgrade to 9.2 on a N3DS. During the middle of installation, I got an error. following the guide, i restarted the 2nd section at 3ds.guide; however, i cannot access the homebrew menu via soundhax. Any suggestions?

**Comment by TheProgramerEX** [comment]
1) I don't think this is the right place to put this.
2) did you read the instructions carefully and made sure you got a audio file for your country?
3) did you try both the 9.2 payload and the payload for the version you were on previously?
4) do you have any other ways of getting into homebrew? have you tried browserhax?

**Comment by falsettoo** [comment]
If you error during your downgrade from 11.1 to 9.2, you have to switch the old 11.1 version of the otherapp.bin. Go back to http://smealum.github.io/3ds/ and redownload the correct version that your system is "partially" downgraded to. After that, continue to use soundhax to get to HBL and retry the downgrade to fill in the missing installations.

**Comment by lolbob181** [comment]
Ye u need to create anothet otherapp.bin from the homebrew starter.zip page for ur device it happend to me ;)
