### ISSUE TITLE
Nintendo 3DS Sound crashes when trying to open "<3 nedwill 2016"

### ISSUE THREAD

**Issue by will933** [nedwill/soundhax#58]
Hey,

I've spent the last hour trying to sort this issue with a very helpful user on #3DShacks on Rizon, to no avail unfortunately. I've also followed the guide to a tee and nothing seems to be working. The issue is, when I try and open the file on Nintendo 3DS Sound it crashes and comes up with an error message stating "An error has occured, forcing the software to close. The system will now restart (Unsaved data may be lost.)" to which all I can do is press "ok". I'm not sure what else to try as I've tried everything, formatted my card a few times, redownloaded the files, tried it with a cartridge in, and etcetera etcetera. I'm definitely using all the correct files as the user that helped me looked at it all and said it's all correct. I've just now tried factory resetting my N3DS and it still doesn't work.

**Comment by will933** [comment]
I've managed to get a tad further. If I play another .mp3 file and then go back and try to play the <3 nedwill 2016 file it flashes red to green and then crashes.

**Comment by will933** [comment]
I've got it working. I, stupidly, renamed the file wrong.

**Comment by MilkstheMage** [comment]
I'm having the same problem, but I correctly named my otherapp.bin file. any help?

**Comment by SilasList** [comment]
Have you gotten this to work i have the same issue but my files are correct.

**Comment by NathanCabigao1** [comment]
some thing happened to me![bitmoji](https://render.bitstrips.com/v2/cpanel/8809984-287321027_1-s1-v1.png?transparent=1&palette=1&width=246)
