### ISSUE TITLE
Old 3ds 11.2.0-35U Red Screen

### ISSUE THREAD

**Issue by seanrayment** [nedwill/soundhax#64]
Playing the sound file on an old 3ds v11.2.0-35U starts the homebrew process but then freezes indefinitely on a red screen instead of launching the homebrew menu.

**Comment by mariogamer2** [comment]
Not a soundhax issues. Verify that you have a boot.3dsx on your sd card. Retry a lot of time.

**Comment by seanrayment** [comment]
It was my mistake, I didn't extract the starter.zip into the SD card.
