### ISSUE TITLE
Not working on 11.0.0.33 2DS

### ISSUE THREAD

**Issue by xXAquaNightXx** [nedwill/soundhax#65]
USA 2DS

After playing the mp4 and colors cycle crashes to home screen with the error "An error has occurred, forcing the software to close. The system will now restart"

Please close I got it to work

**Comment by RustyBallz** [comment]
why did you close this? Did you figure out the issue?

**Comment by xXAquaNightXx** [comment]
Yea i did the renaming wrong I think, this was so long ago lol
