### ISSUE TITLE
Soundhax error for 9.2?

### ISSUE THREAD

**Issue by BluntJoy** [nedwill/soundhax#68]
Hello, I use a n3ds on cfw and fw 9.2 when I load up the m4a file from my media player an error pops up and makes my device restart; what do I do? (P.S. I have the correct file for my region)

**Comment by lolbob181** [comment]
try 11.2?

**Comment by BluntJoy** [comment]
I'm using AuReinand and everytime I update it has an error and won't let me start emunand.

**Comment by deadair3210** [comment]
How long has it been since you updated your CFW, AuReiNAND got discontinued and Luma3DS took its place a while ago

**Comment by BluntJoy** [comment]
I'm on AuReinand 2.1 so it's pretty outdated but I don't know how to update from Rei to Luma. Is that the solution to my issue?

**Comment by deadair3210** [comment]
It could be either you need to update to the latest Luma, or that you need to update your nand, either way this should tell you how to go from aureinand to luma, then you can go from there https://github.com/AuroraWright/Luma3DS/wiki/Installation-and-upgrade

**Comment by BluntJoy** [comment]
Thanks for the feedback; found out I just didn't download my otherapp.bin
