### ISSUE TITLE
Black Screen (top) Red Screen (bottom) freeze after launching. O3DS Firmware 11.2.0-35U

### ISSUE THREAD

**Issue by Robotriceratops** [nedwill/soundhax#77]
Just pulled down the repo and ran through the quick readme. Starter Kit, payload, and m4a only thing things on the root of the SD card aside from the 3DS folder. Song launches and it looks to be working fine.

Flashes to black, white boot text begins to appear. Get the message "the homemenu ropbin ready". Screen flashes green momentarily, more boot text, last message I can see says "boss:p" and than hangs on the red screen.

Any help or info on this issue?

**Comment by yellows8** [comment]
boot.3dsx @ sd-root?

**Comment by Robotriceratops** [comment]
I apologize, I should have read the readme for the Starter Kit closer. While I had the file, it was one deep in the "starter" folder that's included in the zip. 

Thanks for your help and sorry for wasting your time. Maybe possible to consider changing up the Readme here to include verifying the starter pack is unzipped to the right directory level?
