### ISSUE TITLE
11.4.0-37E "Cannot play" Error

### ISSUE THREAD

**Issue by Decloud256** [nedwill/soundhax#85]
Hi guys. 

I sadly updated my new3ds to 11.4.0-37E before i find a guide how to install the cfw on my n3ds.

I used sky3ds before and now wanted to try this way.

I set up a 32 GB mirco SD card. Put the starter files, the correct soundhax-eur-n3ds.m4a and the correct otherapp.bin (N3DS_E_26624_9221.bin) on the main directory of the sd card.

Then i started the sound app on my 3ds.  when i now klick the file ( <3 nedwill 2016 ....)  it says "cannot play" and i get a red cross sign next to the file.

do i do something wrong ? i would be glad if someone would help me. 

thx

Decloud

**Comment by yellows8** [comment]
"Free 3DS Primary Entrypoint <= 11.3"
