### ISSUE TITLE
nedwill 2016 could not play

### ISSUE THREAD

**Issue by deadmemays** [nedwill/soundhax#92]
I'm trying to set up homebrew on my 2DS and it won't work. I've installed everything correctly and put everything in the right areas (I think) and all i get when I try to play it on 3DS sound is an error message that says 'could not be played'. Any help? (My system is in Europe if that helps in any way.)
![help](https://user-images.githubusercontent.com/31313205/29668144-080084de-88d7-11e7-9e29-c62de44e3a24.png)

**Comment by Committee** [comment]
What firmware version are you on right now?

**Comment by deadmemays** [comment]
It doesnt matter i"ve installed homevrew through Rpwng
